
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source "$HOME/.zprezto/aliases.zsh"
source "$HOME/.zprezto/env.zsh"
source "$HOME/.zprezto/load.zsh"

load yazgazan/zsh-rgrep
load yazgazan/zsh-ctrlp
load yazgazan/zsh-complete-dots
load yazgazan/zsh-gi

