
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source "$HOME/.zprezto/aliases.zsh"
source "$HOME/.zprezto/env.zsh"
source "$HOME/.zprezto/load.zsh"
source "$HOME/.zprezto/dirconf.zsh"
source "$HOME/.zprezto/git-extras-completion.zsh"

load yazgazan/zsh-rgrep
load yazgazan/zsh-ctrlp
load yazgazan/zsh-complete-dots
load yazgazan/zsh-gi
load yazgazan/zsh-attach
load yazgazan/zsh-gulp
load yazgazan/zsh-shortcut
load yazgazan/zsh-d
load yazgazan/zsh-git-hist
load yazgazan/vpn-utils
load rupa/z z.sh

